ALFABETO = "abcdefghijklmnopqrstuvwxyz"
NUMEROS = "0123456789"
MATEMATICOS = "+-/*"
LOGICOS = "<>="
LITERAIS = "-$;.,+/*(:)=<>"
ESPACOS = " \n\t"
RESERVADAS = "program|if|then|else|write|begin|end|real|integer"