'''TIPOS DE VARIAVEIS'''
TIPO_INTEIRO = "NUMERO_INTEIRO"
TIPO_REAL = "NUMERO_REAL"

'''OPERADORES MATEMATICOS'''
TIPO_OPERADOR_MAT_MAIS = "OPERADOR_MAIS"
TIPO_OPERADOR_MAT_MENOS = "OPERADOR_MENOS"
TIPO_OPERADOR_MAT_MULT = "OPERADOR_MULTIPLICACAO"
TIPO_OPERADOR_MAT_DIV = "OPERADOR_DIVISAO"

'''OPERADORES LOGICOS'''
TIPO_LOGICO_IGUAL = "LOGICO_IGUAL"
TIPO_LOGICO_DIFERENTE = "LOGICO_DIFERENTE"
TIPO_LOGICO_MAIOR_OU_IGUAL = "LOGICO_MAIOR_IGUAL"
TIPO_LOGICO_MENOR_OU_IGUAL = "LOGICO_MENOR_IGUAL"
TIPO_LOGICO_MAIOR_QUE = "LOGICO_MAIOR_QUE"
TIPO_LOGICO_MENOR_QUE = "LOGICO_MENOR_QUE"

'''PALAVRAS RESERVADAS'''
TIPO_RESERVADA_IF = "RESERVADA_IF"
TIPO_RESERVADA_ELSE = "RESERVADA_ELSE"
TIPO_RESERVADA_THEN = "RESERVADA_THEN"
TIPO_RESERVADA_READ = "RESERVADA_READ"
TIPO_RESERVADA_WRITE = "RESERVADA_WRITE"
TIPO_RESERVADA_ASSIGNMENT = "RESERVADA_ASSIGNMENT"
TIPO_RESERVADA_PROGRAM = "RESERVADA_PROGRAM"
TIPO_RESERVADA_BEGIN = "RESERVADA_BEGIN"
TIPO_RESERVADA_END = "RESERVADA_END."
TIPO_RESERVADA_DOLLAR = "RESERVADA_DOLLAR"

'''LITERAIS'''
TIPO_LITERAL_VIRGULA = ","
TIPO_LITERAL_PONTO_E_VIRGULA = ";"
TIPO_LITERAL_PONTO = "."
TIPO_LITERAL_DOIS_PONTOS = ":"
TIPO_LITERAL_ABRE_PARENTESE = "("
TIPO_LITERAL_FECHA_PARENTESE = ")"