'''TIPOS DE VARIAVEIS'''
TIPO_INTEIRO = "NUMERO INTEIRO"
TIPO_REAL = "NUMERO REAL"

'''OPERADORES MATEMATICOS'''
TIPO_OPERADOR_MAIS = "OPERADOR MAIS"
TIPO_OPERADOR_MENOS = "OPERADOR MENOS"
TIPO_OPERADOR_MULT = "OPERADOR MULTIPLICACAO"
TIPO_OPERADOR_DIV = "OPERADOR DIVISAO"

'''PALAVRAS RESERVADAS'''
TIPO_RESERVADA_IF = "RESERVADA_IF"
TIPO_RESERVADA_ELSE = "RESERVADA_ELSE"
TIPO_RESERVADA_THEN = "RESERVADA_THEN"
TIPO_RESERVADA_READ = "RESERVADA_READ"
TIPO_RESERVADA_WRITE = "RESERVADA_WRITE"
TIPO_RESERVADA_ASSIGNMENT = "RESERVADA_ASSIGNMENT"
TIPO_RESERVADA_PROGRAM = "RESERVADA_PROGRAM"
TIPO_RESERVADA_END = "RESERVADA_END."

'''OPERADORES LOGICOS'''
TIPO_LOGICO_IGUAL = "LOGICO_IGUAL"
TIPO_LOGICO_DIFERENTE = "LOGICO_DIFERENTE"
TIPO_LOGICO_GREATOREQUAL = "LOGICO_MAIOR_IGUAL"
TIPO_LOGICO_LESSOREQUAL = "LOGICO_MENOR_IGUAL"
TIPO_LOGICO_GREATTHAN = "LOGICO_MAIOR_QUE"
TIPO_LOGICO_LESSTHAN = "LOGICO_MENOR_QUE"